### ISSUE TITLE
osx support? 

### ISSUE THREAD

**Issue by chhschou** [Zsh-Packages/firefox-dev#1]
Hi @psprint thanks for bringing this to my attention.

I haven't tried installing firefox-dev with instruction this repo but I can see it may not work for osx due to the url `https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US` redirects to `https://download-installer.cdn.mozilla.net/pub/devedition/releases/72.0b6/mac/en-US/Firefox%2072.0b6.dmg`. The downloaded file is an `dmg` file.  I am happy to contribute some code to extract a `dmg` file, since I already wrote them in `https://github.com/chhschou/dotfiles/blob/a9fd2f73b7250d65a4b1ca9632a9fe5e903b6e6b/.zsh/zplugin/gui_prog_mac.zsh#L2-L11`

**Comment by psprint** [comment]
Great! The code for the `atclone''` ice is currently:
```zsh
# Remove everything except tar.bz2 files and dot-files
rm -rf *~*.tar.bz2(N)
tar jxf *.tar.bz2
mv firefox ff
# Move everything from the ff/ dir into the current dir
mv ff/*(D) . >/dev/null
rmdir ff
```

For the OS X support, I think that there should be an `if [[ $OSTYPE = darwin* ]]` that would wrap the whole code, as there are no overlapping bits in it and in the Linux code.

**Comment by psprint** [comment]
Basing on the snippet you've pointed I've added support for OS X. However, I'm on Linux and cannot test. Could you test the support? By issuing `zplugin pack for firefox-dev`?

**Comment by chhschou** [comment]
I tried the bgn mode, I think it just fell over in the setting up the `sbin`
```
Downloading package.json for firefox-dev
Parsing package.json...
Found the profile `bgn'

Version: 72.0b3
A snippet providing Firefox Developer Edition.

Setting up snippet           firefox-dev... (as firefox-dev)
Downloading `firefox-dev' (with curl, wget, lftp)...
firefox-dev -> firefox.dmg
zpextract: Unpacking the files from: `firefox.dmg'...
"disk2" ejected.
zpextract: Successfully extracted and marked executable the appropriate files (org.mozilla.updater, crashreporter, firefox, firefox-bin, minidump-analyzer, pingsender, plugin-container, org.mozilla.updater) contained in `firefox.dmg'.
bin-gem-node annex: Warning: The sbin'' ice (`firefox-bin -> firefox') didn't match any files
```

This is the content of `~/.zplugin/snippet/firefox-dev`
```
 ~/.zplugin/snippets/firefox-dev  ls -la  
total 3264
lrwxrwxr-x   1 cchou  staff       13 13 Jan 22:25   -> /Applications
drwxr-xr-x   9 cchou  staff      288 13 Jan 22:25 .
drwxr-xr-x  10 cchou  staff      320 13 Jan 22:37 ..
-rw-r--r--   1 cchou  staff    10244 13 Jan 22:25 .DS_Store
-rw-r--r--   1 cchou  staff  1658119 13 Jan 22:25 .VolumeIcon.icns
drwxr-xr-x   2 cchou  staff       64 13 Jan 22:25 ._backup
drwxr-xr-x  16 cchou  staff      512 13 Jan 22:25 ._zplugin
drwxr-xr-x   3 cchou  staff       96 13 Jan 22:25 .background
drwxr-xr-x   3 cchou  staff       96 13 Jan 22:25 Firefox Developer Edition.app
```

**Comment by chhschou** [comment]
Given the .app folder is in the snippet directory if you do `sbin'Firefox\ Developer\ Edition.app/Contents/MacOS/firefox'` it should work

**Comment by psprint** [comment]
Thanks!

I've had to do `sbin"**/firefox-bin -> sbin'`. First, it uses `firefox-bin` because `firefox` sometimes does not work on my machine – I cannot tell when, as it now does work, however I'm sure that running the binary *always* works. Second, it uses `**/…` as the ice has to work on both Linux and OS X.

It should now work. Could you test?

**Comment by chhschou** [comment]
Tested working!

**Comment by psprint** [comment]
That's just great! Thanks!
