### ISSUE TITLE
extend the atclone ice

### ISSUE THREAD

**Issue by chhschou** [Zsh-Packages/firefox-dev#2]
Hi @psprint, how do I extend the `atclone` ice when using a `pack`? 
Use case: On the mac I create an alias for the firefox program after installation, so I can use `spotlight` (a built in shortcut tool) to start firefox. Previously the code I had runs as part of the `atclone` ICE but that doesn't seem available after using the `pack`.

**Comment by psprint** [comment]
By using a plus-sign,  e.g.: atclone'+...' or atclone=+..., etc.

wt., 28 sty 2020, 01:16 użytkownik Chris Chou <notifications@github.com>
napisał:

**Comment by chhschou** [comment]
Are you able to provide an example? I tried `atclone'+install_dotapp'` where `install_dotapp` is a zsh function.

**Comment by psprint** [comment]
```zsh
 zi delete -y firefox-dev
zi pack"bgn" atclone+';print Hi! The ice is: $ZINIT_ICE[atclone]' for firefox-dev
```

The problem was the lacking `;` most probably. I've made a fix to the package so that the`atclone''` ice includes trailing `;`, so your previous snippet should now work :)

**Comment by chhschou** [comment]
Works beautifully thanks!
